# Generated by Django 2.0.3 on 2018-04-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(help_text='File name', max_length=255, verbose_name='File')),
                ('title', models.CharField(help_text='Title to display on web pages', max_length=255, verbose_name='Title')),
                ('url', models.URLField(help_text='Relative or full URL to where the file is', max_length=255, verbose_name='File URL')),
                ('description', models.TextField(blank=True, help_text='Internal Use: File description', verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True, help_text='Full HTML for the project to display on the project         web page.', verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the project for         list pages.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Title of the project', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='description',
            field=models.TextField(blank=True, help_text='Internal Use: help text to understand         what the tag is for.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='term',
            field=models.CharField(help_text='The label that will be displayed for the tag', max_length=255, verbose_name='Term'),
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(to='projects.Files'),
        ),
    ]
