# Generated by Django 2.0.3 on 2018-04-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180401_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='landing_page',
            field=models.BooleanField(default=False),
        ),
    ]
