# Generated by Django 2.0.3 on 2018-05-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the page', max_length=255, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='A brief description of the page for SEO.', verbose_name='Description')),
                ('body', models.TextField(blank=True, help_text='Full HTML for the page.', verbose_name='Body')),
            ],
        ),
    ]
