# Generated by Django 2.0.3 on 2018-05-20 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='SEO friendly URL.', max_length=255, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
